title: The Reyna Lab
logo: /assets/img/reyna.jpg
description: The Reyna Lab at Emory University
quicklinks: <a href="http://emap.fmd.emory.edu/website/campus/index.htm#?queryzoom=Yes&Query=(bldg='1930')">Woodruff Memorial Research Building</a><br>Office 4119<br><a href="https://www.bmi.emory.edu/">Department of Biomedical Informatics</a><br><a href="https://www.emory.edu/">Emory University</a><br>101 Woodruff Circle, 4th Floor East<br>Atlanta, GA 30322<br><a href="mailto:matthew.a.reyna@emory.edu">matthew.a.reyna@emory.edu</a>
show_links: true
google_analytics:
theme: jekyll-theme-minimal
